spring:
  application:
    name: consumer
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    consumer:
      group-id: consumers
      auto-offset-reset: earliest
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: org.example.*,org.example.model.MonitorValueDTO
      bootstrap-servers: localhost:29092
server:
  port: 8080
  error:
    include-message: always